# This rule is not used by the project kube-llmops-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to llmops.kubellmops.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-llmops-operator
    app.kubernetes.io/managed-by: kustomize
  name: finetunerun-viewer-role
rules:
- apiGroups:
  - llmops.kubellmops.io
  resources:
  - finetuneruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - llmops.kubellmops.io
  resources:
  - finetuneruns/status
  verbs:
  - get
