---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - llmops.kubellmops.io
  resources:
  - finetuneruns
  - llmplatforms
  - modeldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llmops.kubellmops.io
  resources:
  - finetuneruns/finalizers
  - llmplatforms/finalizers
  - modeldeployments/finalizers
  verbs:
  - update
- apiGroups:
  - llmops.kubellmops.io
  resources:
  - finetuneruns/status
  - llmplatforms/status
  - modeldeployments/status
  verbs:
  - get
  - patch
  - update
