{{- if .Values.modelLoader.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hf-token
  labels:
    app.kubernetes.io/name: kube-llmops
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: kube-llmops
type: Opaque
data:
  token: {{ .Values.modelLoader.hfToken | b64enc | quote }}
{{- end }}
