{{- if .Values.grafana.enabled }}
{{- if not .Values.grafana.existingSecret }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-grafana-secret" .Release.Name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-secret
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: kube-llmops
type: Opaque
data:
  {{- if $existing }}
  admin-password: {{ index $existing.data "admin-password" }}
  {{- else }}
  admin-password: {{ .Values.grafana.adminPassword | default (randAlphaNum 16) | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
