## Append samples of your project ##
resources:
- modeldeployment_vllm.yaml
- modeldeployment_tei_embedding.yaml
- modeldeployment_tei_reranker.yaml
- modeldeployment_llamacpp.yaml
- llmplatform_minimal.yaml
- llmplatform_full.yaml
- finetunerun_lora.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
