{{- if .Values.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-langfuse
  labels:
    app.kubernetes.io/name: langfuse
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: kube-llmops
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: langfuse
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: langfuse
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: tracing
        app.kubernetes.io/part-of: kube-llmops
    spec:
      containers:
        - name: langfuse
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXTAUTH_SECRET
              value: {{ .Values.auth.nextAuthSecret | quote }}
            - name: SALT
              value: {{ .Values.auth.salt | quote }}
            - name: NEXTAUTH_URL
              value: {{ .Values.externalUrl | default (printf "http://%s-langfuse:%v" $.Release.Name (.Values.service.port | int)) | quote }}
            - name: DATABASE_URL
              {{- if .Values.postgresql.enabled }}
              value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ $.Release.Name }}-langfuse-pg:5432/{{ .Values.postgresql.auth.database }}"
              {{- else }}
              value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ $.Release.Name }}-litellm-pg:5432/{{ .Values.postgresql.auth.database }}"
              {{- end }}
            - name: TELEMETRY_ENABLED
              value: "false"
            {{- if .Values.init.enabled }}
            - name: LANGFUSE_INIT_ORG_ID
              value: {{ .Values.init.orgId | default "kube-llmops" | quote }}
            - name: LANGFUSE_INIT_ORG_NAME
              value: {{ .Values.init.orgName | default "kube-llmops" | quote }}
            - name: LANGFUSE_INIT_PROJECT_ID
              value: {{ .Values.init.projectId | default "kube-llmops" | quote }}
            - name: LANGFUSE_INIT_PROJECT_NAME
              value: {{ .Values.init.projectName | default "kube-llmops" | quote }}
            - name: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
              value: {{ .Values.init.projectPublicKey | quote }}
            - name: LANGFUSE_INIT_PROJECT_SECRET_KEY
              value: {{ .Values.init.projectSecretKey | quote }}
            - name: LANGFUSE_INIT_USER_EMAIL
              value: {{ .Values.init.userEmail | default "admin@kube-llmops.local" | quote }}
            - name: LANGFUSE_INIT_USER_NAME
              value: {{ .Values.init.userName | default "admin" | quote }}
            - name: LANGFUSE_INIT_USER_PASSWORD
              value: {{ .Values.init.userPassword | default "admin" | quote }}
            {{- end }}
            {{- if .Values.oidc.enabled }}
            - name: AUTH_KEYCLOAK_CLIENT_ID
              value: {{ .Values.oidc.clientId | quote }}
            - name: AUTH_KEYCLOAK_CLIENT_SECRET
              value: {{ .Values.oidc.clientSecret | quote }}
            - name: AUTH_KEYCLOAK_ISSUER
              value: {{ .Values.oidc.issuerUrl | quote }}
            - name: AUTH_KEYCLOAK_ALLOW_ACCOUNT_LINKING
              value: "true"
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: 3000
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: 3000
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-langfuse
  labels:
    app.kubernetes.io/name: langfuse
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: kube-llmops
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: langfuse
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
